version: '3.9'
services:
  db:
    image: mongo
    ports:
      - '27017:27017'
    volumes:
    - /home/barry/mongodb/progress:/data/db
    # environment:
    #   - MONGO_INITDB_ROOT_USERNAME=barbara
    #   - MONGO_INITDB_ROOT_PASSWORD=secret

  db-client:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
    #   - ME_CONFIG_MONGODB_ADMINUSERNAME=barbara
    #   - ME_CONFIG_MONGODB_ADMINPASSWORD=secret
      - ME_CONFIG_MONGODB_URL=mongodb://db:27017/
    depends_on:
      - db
# TODO: replace value to env (volume, auth, url)